### ISSUE TITLE
Boolean variable will not parse as the right data type

### ISSUE THREAD

**Issue by kevbook** [Julien-R44/vite-plugin-validate-env#12]
The boolean variable will not parse as the right data type. This is because you're setting `process.env.VITE_BOOLEAN_VARIABLE = parsed value` -- but `process.env[key]` only accepts strings.

```
export default defineConfig({
  plugins: [
    ValidateEnv({
      VITE_BOOLEAN_VARIABLE: Schema.boolean(),
    }),
  ],
})
```

**Comment by Julien-R44** [comment]
Hey! Sorry for taking so long. Fixed with 1.0.0

https://github.com/Julien-R44/vite-plugin-validate-env/releases/tag/v1.0.0
