### ISSUE TITLE
Should error whenever an unvalidated env variable is used

### ISSUE THREAD

**Issue by BrunnerLivio** [Julien-R44/vite-plugin-validate-env#27]
I am looking for a way to ONLY allow using env variables that are defined in my `env.ts` schema.

As an example:

`env.ts`
```typescript
import {defineConfig} from '@julr/vite-plugin-validate-env'
import {z} from 'zod'

export default defineConfig({
  validator: 'zod',
  schema: {
    VITE_LANGUAGE: z.string(),
  },
})
```

In the application code, the following should occur (desired behavior)

`src/app.ts`
```typescript
// ✅ TypeScript: type "string", all good!
import.meta.env.VITE_LANGUAGE

// ❌ TypeScript: Key "VITE_WHATEVER" does not exist
import.meta.env.VITE_WHATEVER
```

**Comment by BrunnerLivio** [comment]
I am aware this is not directly related to this library but rather to Vite's typing of `ImportMetaEnv` (see below). Feel free to close if you think this should not be discussed as part of this project. However I think it would be worth adding a documentation entry in this project's README if we'd find a solution for this - hence why I created an issue here.

`node_modules/vite/types/importMeta.d.ts`
```typescript
interface ImportMetaEnv {
  [key: string]: any
  BASE_URL: string
  MODE: string
  DEV: boolean
  PROD: boolean
  SSR: boolean
}
```


Vite seems to add `[key: string]: any` as a default. I wonder whether there is a way we could overwrite that.  Since we have to use an interface to augment `ImportMetaEnv` and to make the[ module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation) work I am not too sure how though.

I've already tried the following with:

`env.d.ts`
```typescript
type ImportMetaEnvAugmented =
  import('@julr/vite-plugin-validate-env').ImportMetaEnvAugmented<
    typeof import('./src/env').default
  >

interface ImportMetaEnv extends ImportMetaEnvAugmented {
  [key: string]: never
}
```

**Comment by Julien-R44** [comment]
Unfortunately, this is a limitation of typescript and module augmentation: you can't modify a previous declaration. 

The only alternative I see would be to do this: 

```ts
// lib/env.ts
type ImportMetaEnvAugmented =
  import("@julr/vite-plugin-validate-env").ImportMetaEnvAugmented<
    typeof import("../env").default
  >;

export const env: ImportMetaEnvAugmented = import.meta.env
```

And use only this `env` variable to access environment variables
