### ISSUE TITLE
collecting all errors, and see

### ISSUE THREAD

**Issue by reslear** [Julien-R44/vite-plugin-validate-env#5]
hi @Julien-R44 i'm suggest, collect all errors and display before exit all missing variables. 

My case, the build takes 10 minutes, the plugin reports about missing variable. We add a variable, run the build again, again 10 minutes, and so on...

similar feature released in [znv](https://github.com/lostfictions/znv) for backend.

![image](https://user-images.githubusercontent.com/12596485/193158445-caccd107-ae15-4dea-8e9d-168c8b9fed4d.png)

**Comment by Julien-R44** [comment]
Hey dude!
It's a good idea, you're right, thanks. I will try to do it this weekend

However: which build are you talking about? A docker image, or something else? 

Because normally if you are missing an environment variable, the plugin is supposed to warn you before building anything, just after typing `vite build`

**Comment by Julien-R44** [comment]
Btw, thanks for sharing znv. There are a lot of good ideas in there. I'll steal some of them 😋

**Comment by reslear** [comment]
> Hey dude! It's a good idea, you're right, thanks. I will try to do it this weekend
> 
> However: which build are you talking about? A docker image, or something else?
> 
> Because normally if you are missing an environment variable, the plugin is supposed to warn you before building anything, just after typing `vite build`

yes, is `vite build` in docker container on gitlab ci/cd with ionic appflow for mobile deploy

**Comment by Julien-R44** [comment]
Here is the new output : 

![image](https://user-images.githubusercontent.com/8337858/193407552-03e74ca3-7ebd-416b-be2d-55ea4f469559.png)

**Comment by reslear** [comment]
stylish and sensible)
