### ISSUE TITLE
Allow loading from the `envDir` as specified in Vite config

### ISSUE THREAD

**Issue by BenShelton** [Julien-R44/vite-plugin-validate-env#6]
Vite allows specifying an alternate directory for `env` files with the [envDir](https://vitejs.dev/config/shared-options.html#envdir) option, instead of always being the `root`.

Can this be implemented here too instead of always looking in the root for the `env.ts` file and the `.env` files themselves?

**Comment by Julien-R44** [comment]
Thanks for the info, I didn't know. I'll add this quickly!
I should have the time this weekend

**Comment by Julien-R44** [comment]
Added and published in @0.2.1 !
