### ISSUE TITLE
[Bug] Plugin always reports that env variables are not present, but they are

### ISSUE THREAD

**Issue by CerealKiller97** [Julien-R44/vite-plugin-validate-env#7]
Hello,

I've just seen this amazing plugin, and I wanted to put it in my SvelteKit project. I have read the docs a couple of times, and I am still getting the same issues, it says that my variables are not present but they are.

This is how my ```.env``` file looks like:
```
INSTAGRAM_CLIENT_ID=whatever
INSTAGRAM_CLIENT_SECRET=whatever

PUBLIC_SUPABASE_URL=whatever
PUBLIC_SUPABASE_ANON_KEY=whatever
```

I have extracted validation logic to ```env.ts``` file:

```ts filename=env.ts
import { defineConfig, Schema } from '@julr/vite-plugin-validate-env';

export default defineConfig({
	INSTAGRAM_CLIENT_ID: Schema.string(),
	INSTAGRAM_CLIENT_SECRET: Schema.string(),
	PUBLIC_SUPABASE_URL: Schema.string(),
	PUBLIC_SUPABASE_ANON_KEY: Schema.string()
});
```
<img width="416" alt="Screenshot 2023-03-12 at 13 14 02" src="https://user-images.githubusercontent.com/22789589/224543882-8c50b433-053c-4de7-a4bd-5e9f260186d8.png">

**Comment by Julien-R44** [comment]
I'm not familiar with SvelteKit at all but I think they use their own method to load environment variables so I guess the plugin is not compatible.

Let's say I replace your `env.ts` with :

```ts
import { defineConfig, Schema } from "@julr/vite-plugin-validate-env";

export default defineConfig({
  VITE_INSTAGRAM_CLIENT_ID: Schema.string(),
  VITE_INSTAGRAM_CLIENT_SECRET: Schema.string(),
  VITE_PUBLIC_SUPABASE_URL: Schema.string(),
  VITE_PUBLIC_SUPABASE_ANON_KEY: Schema.string(),
});
```

And add the VITE_ prefix to all your variable in your `.env` file
This should work.

However, it is likely that these variables are also injected into the client code. Which you don't want because some of them are sensitive data. Maybe you can try to verify

**Comment by CerealKiller97** [comment]
@Julien-R44 I've tried this way, didn't work, will explore more, I will go through SvelteKit plugin for Vite, will notify you If I find something interesting.

**Comment by Julien-R44** [comment]
Tried on my side and it worked
Feel to share a repo with the issue and I can take a look

**Comment by CerealKiller97** [comment]
@Julien-R44 I've tried it and it's working. Thank you once again!
